version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: backend
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ticket_concert
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  config:
    image: postgres:16
    container_name: config
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ticket_concert
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  controllers:
    image: postgres:16
    container_name: controllers
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres 
      POSTGRES_DB: ticket_concert
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  model:
    image: postgres:16
    container_name: model
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ticket_concert
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  router:
    image: postgres:16
    container_name: router
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ticket_concert
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  socket:
    image: postgres:16
    container_name: socket
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ticket_concert
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  utils:
    image: postgres:16
    container_name: utils
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ticket_concert
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
